/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    customers: CustomerAuthOperations;
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    products: Product;
    categories: Category;
    occasions: Occasion;
    attributes: Attribute;
    'attribute-terms': AttributeTerm;
    addons: Addon;
    tags: Tag;
    media: Media;
    orders: Order;
    carts: Cart;
    customers: Customer;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    occasions: OccasionsSelect<false> | OccasionsSelect<true>;
    attributes: AttributesSelect<false> | AttributesSelect<true>;
    'attribute-terms': AttributeTermsSelect<false> | AttributeTermsSelect<true>;
    addons: AddonsSelect<false> | AddonsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'store-settings': StoreSetting;
  };
  globalsSelect: {
    'store-settings': StoreSettingsSelect<false> | StoreSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Customer | User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Cadastro dos produtos. O preço do lote é calculado sozinho.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Tira o produto da loja e dos anúncios sem apagar nada. Use em item sazonal ou descontinuado.
   */
  archived?: boolean | null;
  featured?: boolean | null;
  /**
   * Preenchido sozinho a partir do nome. Depois que a página estiver no ar, evite mudar: os links dos anúncios usam este endereço.
   */
  slug?: string | null;
  /**
   * Preenchido pela migração, para rastrear a origem do produto.
   */
  legacyWooId?: number | null;
  name: string;
  /**
   * Uma ou duas frases. Aparece na listagem e nos feeds do Google e da Meta.
   */
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * A primeira foto é a principal. Arraste para mudar a ordem. Use imagens de no mínimo 1500x1500 para o Google não reprovar.
   */
  gallery?: (number | Media)[] | null;
  /**
   * Tipo do produto. Ex.: Velas em vidro.
   */
  category?: (number | null) | Category;
  /**
   * Para quais eventos este produto serve. Vira filtro na loja e etiqueta nos anúncios.
   */
  occasions?: (number | Occasion)[] | null;
  tags?: (number | Tag)[] | null;
  /**
   * Ex.: Aroma, com os valores que este produto oferece. Cada combinação vira uma variação, sem preço próprio.
   */
  optionGroups?:
    | {
        attribute: number | Attribute;
        /**
         * Marque só os que este produto tem. Ex.: 6 dos 7 aromas.
         */
        terms: (number | AttributeTerm)[];
        id?: string | null;
      }[]
    | null;
  /**
   * Hoje a Lumini trabalha com um aroma por lote, igual ao site atual. Mudar para "total do pedido" permite misturar aromas dentro do mesmo lote.
   */
  minQtyScope: 'variation' | 'order';
  /**
   * Criadas automaticamente a partir dos valores marcados acima, e atualizadas a cada vez que você salva. Nenhuma tem preço próprio: o preço vem sempre da tabela de lotes.
   */
  variants?:
    | {
        label?: string | null;
        sku?: string | null;
        active?: boolean | null;
        /**
         * Opcional. Se vazio, usa a primeira foto do produto.
         */
        image?: (number | null) | Media;
        key?: string | null;
        termIds?: string | null;
        /**
         * Usado para manter o histórico desta oferta no Google Merchant e no catálogo da Meta.
         */
        legacyWooVariationId?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * É o único preço que você digita. Ex.: 38,00 gera 20 peças = R$ 760,00 e 200 peças = R$ 7.600,00.
   */
  unitPrice: number;
  minQty: number;
  /**
   * Usado para gerar as faixas quando a lista abaixo está vazia.
   */
  qtyStep: number;
  /**
   * Acima disso o botão vira "Solicitar orçamento" no WhatsApp.
   */
  maxQty: number;
  /**
   * As quantidades que aparecem para escolher. Só estas podem ser compradas. Deixe vazio para gerar automaticamente.
   */
  lotSizes?: number[] | null;
  /**
   * Deixe vazio para manter o mesmo preço por peça em todas as faixas, como é hoje. Se preencher, a partir da quantidade informada o preço da peça passa a ser o novo valor.
   */
  volumeDiscounts?:
    | {
        fromQty: number;
        unitPrice: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Calculada a partir do preço da peça. Não é editável de propósito: é o que impede erro de digitação.
   */
  lotTable?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  priceFrom?: number | null;
  priceTo?: number | null;
  /**
   * Ex.: "Frase ou nome para o rótulo" e o envio da logomarca. O texto é impresso exatamente como o cliente digitar.
   */
  personalizationFields?:
    | {
        label: string;
        type: 'text' | 'textarea' | 'file' | 'select' | 'date';
        /**
         * Ex.: Para Luana com amor
         */
        placeholder?: string | null;
        required?: boolean | null;
        /**
         * Ex.: 20 na primeira linha do rótulo, 25 na segunda.
         */
        maxChars?: number | null;
        /**
         * Separe por vírgula. Ex.: Off white, Verde oliva, Rosé
         */
        options?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Cobrados por peça, somados ao lote.
   */
  addons?: (number | Addon)[] | null;
  /**
   * Em dias úteis. O site soma este prazo ao da transportadora e mostra a data prevista. O mesmo valor alimenta a entrega estimada no Google.
   */
  productionDays?:
    | {
        fromQty: number;
        minDays: number;
        maxDays: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Peso e medidas da caixa usada em cada faixa. É o que o Melhor Envio usa para cotar. Sem isso, a cotação de lotes grandes falha.
   */
  packaging?:
    | {
        fromQty: number;
        boxes: number;
        weightKg: number;
        widthCm: number;
        heightCm: number;
        lengthCm: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Vira a tabela de informações na página do produto.
   */
  techSheet?: {
    durationHours?: number | null;
    weight?: string | null;
    height?: string | null;
    width?: string | null;
    container?: string | null;
    includes?: string | null;
    shelfLifeMonths?: number | null;
  };
  /**
   * Matéria-prima, embalagem e mão de obra. Entra no DRE como custo do produto vendido. Fica gravado no pedido no dia da venda.
   */
  unitCost?: number | null;
  /**
   * Velas fabricadas vão no Anexo II; itens revendidos, no Anexo I.
   */
  fiscalAnnex?: ('II' | 'I') | null;
  /**
   * Velas: 3406.00.00.
   */
  ncm?: string | null;
  csosn?: string | null;
  cfopInternal?: string | null;
  cfopInterstate?: string | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  /**
   * Velas: 588 (Home & Garden > Decor > Home Fragrances > Candles).
   */
  googleProductCategory?: string | null;
  /**
   * Marque apenas se este produto já tem histórico aprovado no Google Merchant. Assim ele não é tratado como produto novo e não perde desempenho.
   */
  preserveLegacyFeedId?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Fotos dos produtos e arquivos enviados pelos clientes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descreva a foto em poucas palavras. Ajuda no Google e em leitores de tela. Ex.: "Vela aromática em bomboniere de cristal com laço de cetim".
   */
  alt: string;
  /**
   * Opcional. Se a foto é de um evento real, registre de quem é a autorização.
   */
  credit?: string | null;
  kind?: ('produto' | 'evento' | 'logo_cliente' | 'prova_arte' | 'outro') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feed?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Tipo de produto. Ex.: Velas em vidro, Difusores.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Preenchido sozinho a partir do nome. Depois que a página estiver no ar, evite mudar: os links dos anúncios usam este endereço.
   */
  slug?: string | null;
  /**
   * Deixe vazio se for uma categoria principal.
   */
  parent?: (number | null) | Category;
  description?: string | null;
  image?: (number | null) | Media;
  sortOrder?: number | null;
  legacyWooId?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Casamento, bodas, 15 anos, batizado, maternidade, corporativo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "occasions".
 */
export interface Occasion {
  id: number;
  name: string;
  /**
   * Preenchido sozinho a partir do nome. Depois que a página estiver no ar, evite mudar: os links dos anúncios usam este endereço.
   */
  slug?: string | null;
  /**
   * Ex.: "Lembrancinhas de casamento feitas à mão".
   */
  headline?: string | null;
  description?: string | null;
  heroImage?: (number | null) | Media;
  /**
   * Ex.: "60 a 200 peças". Aparece como orientação de quantidade para este tipo de evento.
   */
  suggestedLots?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Palavras-chave livres. Use com parcimônia.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  /**
   * Preenchido sozinho a partir do nome. Depois que a página estiver no ar, evite mudar: os links dos anúncios usam este endereço.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Listas reutilizadas em vários produtos, como os aromas.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attributes".
 */
export interface Attribute {
  id: number;
  name: string;
  /**
   * Preenchido sozinho a partir do nome. Depois que a página estiver no ar, evite mudar: os links dos anúncios usam este endereço.
   */
  slug?: string | null;
  displayType?: ('button' | 'image' | 'color' | 'select') | null;
  /**
   * Opcional. Aparece como ajuda ao cliente.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Ex.: os aromas Bamboo, Lavanda, Vanilla.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attribute-terms".
 */
export interface AttributeTerm {
  id: number;
  attribute: number | Attribute;
  name: string;
  /**
   * Preenchido sozinho a partir do nome. Depois que a página estiver no ar, evite mudar: os links dos anúncios usam este endereço.
   */
  slug?: string | null;
  /**
   * Usada quando a opção aparece como miniatura, ex.: modelos de flor.
   */
  image?: (number | null) | Media;
  /**
   * Usada quando a opção aparece como bolinha de cor. Ex.: #E8D9C5.
   */
  colorHex?: string | null;
  /**
   * Menor aparece primeiro.
   */
  sortOrder?: number | null;
  /**
   * Preenchido pela migração. Não editar.
   */
  legacyWooTermId?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Itens cobrados à parte, como laço, caixa e flores secas.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addons".
 */
export interface Addon {
  id: number;
  name: string;
  /**
   * Preenchido sozinho a partir do nome. Depois que a página estiver no ar, evite mudar: os links dos anúncios usam este endereço.
   */
  slug?: string | null;
  /**
   * Aparece ao lado da opção na página do produto.
   */
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * Multiplica pela quantidade do lote. Ex.: R$ 1,50 por peça em 60 peças = R$ 90,00.
   */
  pricePerUnit?: number | null;
  /**
   * Cobrado uma vez por pedido, independente da quantidade. Use um ou outro.
   */
  flatPrice?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Todos os pedidos, do site e os lançados à mão.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  number: string;
  status:
    | 'pending'
    | 'processing'
    | 'art_approval'
    | 'production'
    | 'shipped'
    | 'completed'
    | 'cancelled'
    | 'refunded'
    | 'failed'
    | 'disputed';
  /**
   * Usado para medir o retorno de cada canal e devolver a conversão à Meta.
   */
  channel: 'site' | 'whatsapp' | 'instagram_dm' | 'admin';
  legacyWooId?: number | null;
  customerName: string;
  email?: string | null;
  phone?: string | null;
  personType?: ('PF' | 'PJ') | null;
  document?: string | null;
  customer?: (number | null) | Customer;
  /**
   * Nome, preço e custo ficam congelados no momento da venda, para o histórico não mudar depois.
   */
  items?:
    | {
        product?: (number | null) | Product;
        productName: string;
        variantLabel?: string | null;
        sku?: string | null;
        qty: number;
        unitPrice: number;
        lotPrice: number;
        lineTotal: number;
        /**
         * O que o cliente escreveu, exatamente como digitou.
         */
        personalization?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        addons?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        artFile?: (number | null) | Media;
        artProof?: (number | null) | Media;
        /**
         * Congelado na venda. Alimenta o lucro no DRE.
         */
        unitCost?: number | null;
        id?: string | null;
      }[]
    | null;
  shippingAddress?: {
    postalCode?: string | null;
    street?: string | null;
    number?: string | null;
    complement?: string | null;
    district?: string | null;
    city?: string | null;
    state?: string | null;
  };
  shippingService?: string | null;
  trackingCode?: string | null;
  /**
   * Casamento, 15 anos, batizado...
   */
  eventType?: string | null;
  /**
   * O prazo de produção precisa caber antes desta data.
   */
  eventDate?: string | null;
  /**
   * Data limite calculada no momento da compra.
   */
  productionDeadline?: string | null;
  customerNote?: string | null;
  subtotal: number;
  shippingTotal?: number | null;
  discountTotal?: number | null;
  total: number;
  paymentMethod?: ('pix' | 'credit_card' | 'debit_card' | 'mp_link' | 'external') | null;
  installments?: number | null;
  couponCode?: string | null;
  /**
   * Preenchido sozinho quando o pagamento é confirmado.
   */
  mercadoPago?: {
    paymentId?: string | null;
    status?: string | null;
    /**
     * Valor real informado pelo Mercado Pago.
     */
    feeCents?: number | null;
    netReceivedCents?: number | null;
    /**
     * Usada no fluxo de caixa, que é diferente do DRE.
     */
    moneyReleaseDate?: string | null;
  };
  datePaid?: string | null;
  /**
   * Aquele código curto que vai na mensagem do WhatsApp.
   */
  leadRef?: string | null;
  /**
   * Campanha, anúncio e cookies capturados na visita.
   */
  attribution?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Registro do que já foi para a Meta e para o Google, para não enviar duas vezes.
   */
  conversionsSent?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Tudo que aconteceu com o pedido, na ordem.
   */
  events?:
    | {
        at?: string | null;
        type?: string | null;
        message?: string | null;
        actor?: string | null;
        id?: string | null;
      }[]
    | null;
  notes?:
    | {
        visibleToCustomer?: boolean | null;
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Quem compra na loja.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  name?: string | null;
  phone?: string | null;
  personType?: ('PF' | 'PJ') | null;
  /**
   * Necessário para emitir a nota fiscal.
   */
  document?: string | null;
  addresses?:
    | {
        label?: string | null;
        postalCode: string;
        street: string;
        number: string;
        complement?: string | null;
        district: string;
        city: string;
        state: string;
        isDefault?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Guardadas com data e hora, como prova de consentimento exigida pela LGPD e pela política do WhatsApp.
   */
  optIns?: {
    whatsappStatus?: boolean | null;
    marketing?: boolean | null;
    log?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  /**
   * Marque se o cliente pediu para não ter os dados usados em anúncios.
   */
  metaOptOut?: boolean | null;
  legacyWooId?: number | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * Carrinhos em aberto e abandonados.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  token: string;
  status: 'active' | 'abandoned' | 'converted' | 'lost';
  items?:
    | {
        product: number | Product;
        variantKey?: string | null;
        qty: number;
        /**
         * O que o cliente escreveu em cada campo.
         */
        personalization?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        addonIds?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Capturado no primeiro passo do checkout, para recuperar o carrinho.
   */
  email?: string | null;
  phone?: string | null;
  /**
   * Preenchido quando o cliente entra na conta.
   */
  customer?: (number | null) | Customer;
  couponCode?: string | null;
  lastActivityAt?: string | null;
  convertedOrderNumber?: string | null;
  /**
   * De onde o cliente veio: campanha, anúncio ou acesso direto.
   */
  attribution?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Quem pode entrar no painel e o que cada pessoa enxerga.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Dono: acesso total. Atendente: pedidos, clientes e orçamentos. Designer: só personalização e prova de arte.
   */
  role: 'dono' | 'atendente' | 'designer';
  /**
   * Opcional. Para receber avisos de pedido novo.
   */
  whatsapp?: string | null;
  notifyOnNewOrder?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'occasions';
        value: number | Occasion;
      } | null)
    | ({
        relationTo: 'attributes';
        value: number | Attribute;
      } | null)
    | ({
        relationTo: 'attribute-terms';
        value: number | AttributeTerm;
      } | null)
    | ({
        relationTo: 'addons';
        value: number | Addon;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'customers';
        value: number | Customer;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'customers';
        value: number | Customer;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  archived?: T;
  featured?: T;
  slug?: T;
  legacyWooId?: T;
  name?: T;
  shortDescription?: T;
  description?: T;
  gallery?: T;
  category?: T;
  occasions?: T;
  tags?: T;
  optionGroups?:
    | T
    | {
        attribute?: T;
        terms?: T;
        id?: T;
      };
  minQtyScope?: T;
  variants?:
    | T
    | {
        label?: T;
        sku?: T;
        active?: T;
        image?: T;
        key?: T;
        termIds?: T;
        legacyWooVariationId?: T;
        id?: T;
      };
  unitPrice?: T;
  minQty?: T;
  qtyStep?: T;
  maxQty?: T;
  lotSizes?: T;
  volumeDiscounts?:
    | T
    | {
        fromQty?: T;
        unitPrice?: T;
        id?: T;
      };
  lotTable?: T;
  priceFrom?: T;
  priceTo?: T;
  personalizationFields?:
    | T
    | {
        label?: T;
        type?: T;
        placeholder?: T;
        required?: T;
        maxChars?: T;
        options?: T;
        id?: T;
      };
  addons?: T;
  productionDays?:
    | T
    | {
        fromQty?: T;
        minDays?: T;
        maxDays?: T;
        id?: T;
      };
  packaging?:
    | T
    | {
        fromQty?: T;
        boxes?: T;
        weightKg?: T;
        widthCm?: T;
        heightCm?: T;
        lengthCm?: T;
        id?: T;
      };
  techSheet?:
    | T
    | {
        durationHours?: T;
        weight?: T;
        height?: T;
        width?: T;
        container?: T;
        includes?: T;
        shelfLifeMonths?: T;
      };
  unitCost?: T;
  fiscalAnnex?: T;
  ncm?: T;
  csosn?: T;
  cfopInternal?: T;
  cfopInterstate?: T;
  metaTitle?: T;
  metaDescription?: T;
  googleProductCategory?: T;
  preserveLegacyFeedId?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  parent?: T;
  description?: T;
  image?: T;
  sortOrder?: T;
  legacyWooId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "occasions_select".
 */
export interface OccasionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  headline?: T;
  description?: T;
  heroImage?: T;
  suggestedLots?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attributes_select".
 */
export interface AttributesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  displayType?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attribute-terms_select".
 */
export interface AttributeTermsSelect<T extends boolean = true> {
  attribute?: T;
  name?: T;
  slug?: T;
  image?: T;
  colorHex?: T;
  sortOrder?: T;
  legacyWooTermId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addons_select".
 */
export interface AddonsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  image?: T;
  pricePerUnit?: T;
  flatPrice?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  kind?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feed?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  number?: T;
  status?: T;
  channel?: T;
  legacyWooId?: T;
  customerName?: T;
  email?: T;
  phone?: T;
  personType?: T;
  document?: T;
  customer?: T;
  items?:
    | T
    | {
        product?: T;
        productName?: T;
        variantLabel?: T;
        sku?: T;
        qty?: T;
        unitPrice?: T;
        lotPrice?: T;
        lineTotal?: T;
        personalization?: T;
        addons?: T;
        artFile?: T;
        artProof?: T;
        unitCost?: T;
        id?: T;
      };
  shippingAddress?:
    | T
    | {
        postalCode?: T;
        street?: T;
        number?: T;
        complement?: T;
        district?: T;
        city?: T;
        state?: T;
      };
  shippingService?: T;
  trackingCode?: T;
  eventType?: T;
  eventDate?: T;
  productionDeadline?: T;
  customerNote?: T;
  subtotal?: T;
  shippingTotal?: T;
  discountTotal?: T;
  total?: T;
  paymentMethod?: T;
  installments?: T;
  couponCode?: T;
  mercadoPago?:
    | T
    | {
        paymentId?: T;
        status?: T;
        feeCents?: T;
        netReceivedCents?: T;
        moneyReleaseDate?: T;
      };
  datePaid?: T;
  leadRef?: T;
  attribution?: T;
  conversionsSent?: T;
  events?:
    | T
    | {
        at?: T;
        type?: T;
        message?: T;
        actor?: T;
        id?: T;
      };
  notes?:
    | T
    | {
        visibleToCustomer?: T;
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  token?: T;
  status?: T;
  items?:
    | T
    | {
        product?: T;
        variantKey?: T;
        qty?: T;
        personalization?: T;
        addonIds?: T;
        id?: T;
      };
  email?: T;
  phone?: T;
  customer?: T;
  couponCode?: T;
  lastActivityAt?: T;
  convertedOrderNumber?: T;
  attribution?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  personType?: T;
  document?: T;
  addresses?:
    | T
    | {
        label?: T;
        postalCode?: T;
        street?: T;
        number?: T;
        complement?: T;
        district?: T;
        city?: T;
        state?: T;
        isDefault?: T;
        id?: T;
      };
  optIns?:
    | T
    | {
        whatsappStatus?: T;
        marketing?: T;
        log?: T;
      };
  metaOptOut?: T;
  legacyWooId?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  whatsapp?: T;
  notifyOnNewOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Dados da empresa, prazos, parcelamento e textos legais.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-settings".
 */
export interface StoreSetting {
  id: number;
  /**
   * Nome registrado da empresa, como consta no CNPJ.
   */
  legalName: string;
  tradeName?: string | null;
  cnpj: string;
  /**
   * Necessária para emitir nota fiscal. Deixe vazio se a empresa for isenta.
   */
  stateRegistration?: string | null;
  address?: {
    street?: string | null;
    number?: string | null;
    complement?: string | null;
    district?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
  };
  email?: string | null;
  /**
   * Só números, com o 55 na frente.
   */
  whatsapp?: string | null;
  /**
   * Ex.: Segunda a sexta, das 9h às 18h.
   */
  businessHours?: string | null;
  /**
   * Usadas quando um produto novo não define faixas próprias. As mesmas do site atual.
   */
  defaultLotSizes?: number[] | null;
  defaultMinQty?: number | null;
  defaultMaxQty?: number | null;
  /**
   * Aparece na loja inteira. Ex.: "Produção atual: 15 dias úteis". Deixe vazio para esconder.
   */
  productionBanner?: string | null;
  /**
   * Nos meses de pico (casamentos e brindes de fim de ano) a loja deixa de oferecer prazo reduzido.
   */
  rushBlackout?: {
    from?: string | null;
    to?: string | null;
  };
  /**
   * Acima disso o cliente paga os juros. Atenção: 12x sem juros custa cerca de 21,8% da venda para a loja.
   */
  maxInterestFreeInstallments?: number | null;
  /**
   * Deixe vazio ou zero para não oferecer frete grátis.
   */
  freeShippingFrom?: number | null;
  /**
   * Precisa dizer com clareza que o cliente pode desistir em 7 dias corridos após receber, mesmo em produto personalizado, e como fazer isso.
   */
  returnPolicy?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  termsOfUse?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Deve listar quais dados são coletados, com que base legal, com quem são compartilhados (Mercado Pago, Melhor Envio, Meta, Google) e por quanto tempo ficam guardados.
   */
  privacyPolicy?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Mude ao alterar as políticas. A versão aceita fica gravada em cada pedido, como prova.
   */
  legalVersion?: string | null;
  /**
   * As chaves ficam nas variáveis de ambiente, nunca aqui. Este campo é só para anotações.
   */
  integrationsNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-settings_select".
 */
export interface StoreSettingsSelect<T extends boolean = true> {
  legalName?: T;
  tradeName?: T;
  cnpj?: T;
  stateRegistration?: T;
  address?:
    | T
    | {
        street?: T;
        number?: T;
        complement?: T;
        district?: T;
        city?: T;
        state?: T;
        postalCode?: T;
      };
  email?: T;
  whatsapp?: T;
  businessHours?: T;
  defaultLotSizes?: T;
  defaultMinQty?: T;
  defaultMaxQty?: T;
  productionBanner?: T;
  rushBlackout?:
    | T
    | {
        from?: T;
        to?: T;
      };
  maxInterestFreeInstallments?: T;
  freeShippingFrom?: T;
  returnPolicy?: T;
  termsOfUse?: T;
  privacyPolicy?: T;
  legalVersion?: T;
  integrationsNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}